/* Generated by Yosys 0.41+24 (git sha1 165791769, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -Os) */

module and2(a, b, c);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  wire a;
  input b;
  wire b;
  output c;
  wire c;
  assign c = 4'h8 >> { a, b };
  assign _0_ = 1'h0;
  assign _1_ = 1'h1;
  assign _2_ = 1'hx;
endmodule
