# Fabric generation configuration file
# = = = = = = = = = = = = = = = = = = =
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
# timeout_each_job : FPGA Task script splits fpga flow into multiple jobs
# Each job execute fpga_flow script on combination of architecture & benchmark
# timeout_each_job is timeout for each job
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
    
[GENERAL]
run_engine=openfpga_shell
power_tech_file = /mnt/vault1/rsunketa/OpenFPGA/openfpga_flow/tech/PTM_45nm/45nm.xml
power_analysis =false
spice_output=false
verilog_output=true
timeout_each_job = 20*60
fpga_flow=yosys_vpr
    
[OpenFPGA_SHELL]
openfpga_shell_template=/mnt/vault1/rsunketa/OpenFPGA/openfpga_noc/pbf_scripts/templates/fabric_gen_shell_script.openfpga
openfpga_arch_file=/mnt/vault1/rsunketa/OpenFPGA/openfpga_noc/pbf_scripts/tt/collateral/arch/openfpga_arch.xml
openfpga_sim_setting_file=/mnt/vault1/rsunketa/OpenFPGA/openfpga_flow/openfpga_simulation_settings/fixed_sim_openfpga.xml
    
openfpga_vpr_device_layout=large
    
[ARCHITECTURES]
arch0=/mnt/vault1/rsunketa/OpenFPGA/openfpga_noc/results/arch/mesh_4x4_complexDSP_mem32k_hbm_eth_vpr.xml
# arch0=/mnt/vault1/rsunketa/OpenFPGA/openfpga_noc/results/arch/baseline_complexDSP_mem32k_hbm_eth_vpr.xml
    
[BENCHMARKS]
# bench0=/mnt/vault1/rsunketa/vtr-verilog-to-routing/vtr_flow/benchmarks/verilog/koios_proxy/proxy.6.v
# bench0=/mnt/vault1/rsunketa/OpenFPGA/openfpga_noc/results/benchmarks/koios_axi_wrap.v
bench0=/mnt/vault1/rsunketa/OpenFPGA/openfpga_noc/results/benchmarks/hard_noc/pe_12_noc.v
# /mnt/vault1/rsunketa/OpenFPGA/openfpga_noc/results/benchmarks/soft_noc/pe_12_switch.v
# /mnt/vault1/rsunketa/OpenFPGA/openfpga_noc/results/benchmarks/soft_noc/pe_4_switch.v
    
[SYNTHESIS_PARAM]
# Yosys script parameters
bench0_top = pe_12_noc
# bench0_top = koios_axi_wrap
# bench0_top = pe_12_switch
bench0_yosys = /mnt/vault1/rsunketa/OpenFPGA/openfpga-test-runs/001-shashank-router-tasks/scripts/complete_ys_tmpl.ys
bench_read_verilog_options_common = -nolatches
bench_yosys_cell_sim_verilog_common=/mnt/vault1/rsunketa/OpenFPGA/openfpga_flow/openfpga_yosys_techlib/k6_frac_N10_tileable_adder_chain_dpram32K_dsp36_fracff_40nm_cell_sim.v
bench_yosys_dff_map_verilog_common=/mnt/vault1/rsunketa/OpenFPGA/openfpga_flow/openfpga_yosys_techlib/k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_fracff_40nm_dff_map.v
bench_yosys_bram_map_rules_common=/mnt/vault1/rsunketa/OpenFPGA/openfpga_flow/openfpga_yosys_techlib/k6_frac_N10_tileable_adder_chain_dpram32K_dsp36_40nm_bram.txt
bench_yosys_bram_map_verilog_common=/mnt/vault1/rsunketa/OpenFPGA/openfpga_flow/openfpga_yosys_techlib/k6_frac_N10_tileable_adder_chain_dpram32K_dsp36_40nm_bram_map.v
bench_yosys_dsp_map_verilog_common=/mnt/vault1/rsunketa/OpenFPGA/openfpga_flow/openfpga_yosys_techlib/k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_40nm_dsp_map.v
bench_yosys_dsp_map_parameters_common=-D DSP_A_MAXWIDTH=36 -D DSP_B_MAXWIDTH=36 -D DSP_A_MINWIDTH=2 -D DSP_B_MINWIDTH=2 -D DSP_NAME=mult_36x36
    
[SCRIPT_PARAM_MIN_ROUTE_CHAN_WIDTH]
#end_flow_with_test=
#vpr_fpga_verilog_formal_verification_top_netlist=
