/* Generated by Yosys 0.41+24 (git sha1 165791769, g++ 9.4.0-1ubuntu1~20.04.2 -fPIC -Os) */

module mac_2(\a[0] , \a[1] , \b[0] , \b[1] , \c[0] , \c[1] , \out[0] , \out[1] );
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input \a[0] ;
  wire \a[0] ;
  input \a[1] ;
  wire \a[1] ;
  input \b[0] ;
  wire \b[0] ;
  input \b[1] ;
  wire \b[1] ;
  input \c[0] ;
  wire \c[0] ;
  input \c[1] ;
  wire \c[1] ;
  output \out[0] ;
  wire \out[0] ;
  output \out[1] ;
  wire \out[1] ;
  assign \out[1]  = 16'h6999 >> { \b[0] , \a[1] , _0_, \c[1]  };
  assign _0_ = 16'hd777 >> { \b[0] , \c[0] , \b[1] , \a[0]  };
  assign \out[0]  = 8'h6a >> { \a[0] , \b[0] , \c[0]  };
  assign _1_ = 1'h0;
  assign _2_ = 1'h1;
  assign _3_ = 1'hx;
endmodule
