#############################################
#	Synopsys Design Constraints (SDC)
#	For FPGA fabric 
#	Description: Disable configurable memory outputs for PnR
#	Author: Xifan TANG 
#	Organization: University of Utah 
#	Date: Mon May 20 15:31:31 2024
#############################################

set_disable_timing fpga_top/grid_io_bottom_bottom_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/EMBEDDED_IO_ISOLN_DFFRQ_mem/DFFRQ_*_/Q
set_disable_timing fpga_top/grid_io_right_right_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/EMBEDDED_IO_ISOLN_DFFRQ_mem/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/grid_io_top_top_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/EMBEDDED_IO_ISOLN_DFFRQ_mem/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/grid_io_left_left_*__*_/logical_tile_io_mode_io__*/logical_tile_io_mode_physical__iopad_*/EMBEDDED_IO_ISOLN_DFFRQ_mem/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_mode_default__frac_lut*_*/frac_lut*_DFFRQ_mem/DFFRQ_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_*/mem_frac_logic_out_*/DFFRQ_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_mode_default__frac_logic_*/mem_frac_lut*_*_in_*/DFFRQ_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/mem_fabric_out_*/DFFRQ_*_/Q
set_disable_timing fpga_top/grid_clb_*__*_/logical_tile_clb_mode_clb__*/logical_tile_clb_mode_default__fle_*/logical_tile_clb_mode_default__fle_mode_physical__fabric_*/mem_ff_*_D_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_bottom_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_left_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cbx_*__*_/mem_top_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_right_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/cby_*__*_/mem_right_ipin_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_top_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_bottom_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
set_disable_timing fpga_top/sb_*__*_/mem_left_track_*/DFFRQ_*_/Q
